apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
 name: db-team
 namespace: default
 description: Team responsible for database services
spec:
 type: team
 profile:
   displayName: Database Team
