# User: Developer
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alice-dev
spec:
  profile:
    displayName: Alice Developer
    email: alice@example.com
  memberOf: [team-dev]

# User: SRE
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: doug-platform
spec:
  profile:
    displayName: Doug Platform
    email: doug@example.com
  memberOf: [team-pe]

# User: Administrator
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bob-admin
spec:
  profile:
    displayName: Bob Admin
    email: bob@example.com
  memberOf: [team-admin]

# User: Data Scientist
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jack-datascientist
spec:
  profile:
    displayName: Jack Data Scientist
    email: jack@example.com
  memberOf: [team-datasci]

# Group: Developers
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-dev
spec:
  type: team
  profile:
    displayName: Developer Team
    email: devteam@example.com
  children: []
  members: [alice-developer]

# Group: PEs
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-pe
spec:
  type: team
  profile:
    displayName: PE Team
    email: peteam@example.com
  children: []
  members: [sam-sre]

# Group: Admins
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-admin
spec:
  type: team
  profile:
    displayName: Admin Team
    email: adminteam@example.com
  children: []
  members: [bob-admin]

# Group: Data Scientists
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-datasci
spec:
  type: team
  profile:
    displayName: Data Science Team
    email: datasci@example.com
  children: []
  members: [jack-datascientist]
