apiVersion: backstage.io/v1alpha1
kind: Resource # Or your custom PowerStore kind
metadata:
  name: powerstore-iac # A unique, human-readable name
  description: PowerStore appliance in the csc
  annotations:
    backstage.io/techdocs-ref: value
  tags:
    - storage
    - powerstore
    - csc
  links:
    - url: https://172.24.185.60 # Link to the PowerStore UI
      title: PowerStore Manager UI
      icon: dashboard
    - url: https://172.24.185.60/api/rest # Link to monitoring
      title: Volumes
      icon: storage
spec:
  type: storage-array # A specific type for resources
  owner: group:default/storage-team # Define ownership
  system: system:default/infrastructure # Associate with a system